### ISSUE TITLE
komet: interval-role action consumers not migrated to BigDecimal (decimal-interval) — won't compile against elk 0.40.0

### ISSUE THREAD

**Issue by knowledge-graphlet** [IKE-Network/ike-issues#688]
## Symptom

After bumping elk-snomed to 0.40.0 (#687), the Komet installer build fails compiling `komet/rules`:

```
AddIntervalRole.java:[42,102] incompatible types: int cannot be converted to BigDecimal
```

## Root cause

The decimal-interval migration (elk Interval int->BigDecimal; tinkar-core `LogicalExpressionBuilder.IntervalRole(... BigDecimal ...)` / `updateIntervalRoleValue(... BigDecimal ...)`) was applied to elk + tinkar-core but **not to komet's interval-role action consumers**. Two komet/rules files still pass `int` bound values:

- `AddIntervalRole.java:42` — `leb.IntervalRole(concept, 0, true, 10, true, ...)` (int literals)
- `ChangeIntervalBound.java:59` — `int value = Integer.parseInt(...)` then `interval.setLowerBound(value)` / `setUpperBound(value)`

(The other interval files — `ChangeIntervalBoundOpen`, `ChangeIntervalRoleType`, `ChangeIntervalRoleUnitOfMeasure`, `ChangeIntervalValuesMenu`, `RulesBase`, `AxiomFocusedRules`, framework `ClauseView` — don't carry numeric bound values; no change needed. A `SetValueDecimal` helper already exists in the package, confirming the intended decimal pattern.)

## Fix (mechanical)

- `AddIntervalRole`: `0`/`10` -> `BigDecimal.valueOf(0)`/`BigDecimal.valueOf(10)`.
- `ChangeIntervalBound`: `Integer.parseInt` -> `new BigDecimal(...)` (decimal bounds); error message "Enter an integer" -> "Enter a number".

**Note for review:** this is the komet half of emays' decimal-interval feature; the int->decimal change means interval bounds now accept decimals in the UI. Semantics/tests should be reviewed by the feature owner.

Blocks the Komet checkpoint. Surfaced after #687 (elk version bump) let the build reach komet compilation.
